// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR5m0OLQKrGTOnpRSiayegiHR79npSSa8',
    appId: '1:987664653060:web:e547f856e164c547054e51',
    messagingSenderId: '987664653060',
    projectId: 'fet-loginsign',
    authDomain: 'fet-loginsign.firebaseapp.com',
    storageBucket: 'fet-loginsign.firebasestorage.app',
    measurementId: 'G-MBKEH518TN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoCDGF5ZLaRE31nXwv6j_-Ub03oHoDmBs',
    appId: '1:987664653060:android:625ae88e5d07b955054e51',
    messagingSenderId: '987664653060',
    projectId: 'fet-loginsign',
    storageBucket: 'fet-loginsign.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPLCgxRqsjxD_RLKRMzoY5PfPKebYTsR0',
    appId: '1:987664653060:ios:e49a8bba9b035e66054e51',
    messagingSenderId: '987664653060',
    projectId: 'fet-loginsign',
    storageBucket: 'fet-loginsign.firebasestorage.app',
    iosBundleId: 'com.example.fetEventApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPLCgxRqsjxD_RLKRMzoY5PfPKebYTsR0',
    appId: '1:987664653060:ios:e49a8bba9b035e66054e51',
    messagingSenderId: '987664653060',
    projectId: 'fet-loginsign',
    storageBucket: 'fet-loginsign.firebasestorage.app',
    iosBundleId: 'com.example.fetEventApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR5m0OLQKrGTOnpRSiayegiHR79npSSa8',
    appId: '1:987664653060:web:132923a624f60c8b054e51',
    messagingSenderId: '987664653060',
    projectId: 'fet-loginsign',
    authDomain: 'fet-loginsign.firebaseapp.com',
    storageBucket: 'fet-loginsign.firebasestorage.app',
    measurementId: 'G-2NXMV7YKXR',
  );
}
